### ISSUE TITLE
Error generated in AnnotationTypeHelper

### ISSUE THREAD

**Issue by ADmad** [slevomat/coding-standard#709]
The following error is generated when a docblock with typehint of kind `@var array{serialize:string|bool|null}` is encountered.

```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: Undefined property: PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode::$name in
   |       | .../vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php on line 167
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ADmad** [comment]
Perhaps changing the line in question from
```php
		return $typeNode instanceof ThisTypeNode
			? (string) $typeNode
			: $typeNode->name;
```
to just
```php
		return (string) $typeNode;
```
should suffice.

**Comment by ADmad** [comment]
Or maybe additional changes are required further up the call changes to account for the new support for array shapes added to the phpdoc parser https://github.com/phpstan/phpdoc-parser/releases/tag/0.3.5.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/896e52a167a1ebfe6d4a84835cf545181ba23796

**Comment by ADmad** [comment]
Welcome.

I see the milestone has been set to `5.1.0` for this issue. Shouldn't the fix go into next bugfix/patch release for `5.0`?

**Comment by ADmad** [comment]
Any ETA on when this fix will be released? It's causing our CakePHP builds to fail :slightly_smiling_face:

**Comment by kiler129** [comment]
@kukulich Update of the deps doesn't solve the problem.

```
$ composer show phpstan/phpdoc-parser | grep version
versions : * 0.3.5
```

```
$ vendor/bin/phpcs --standard=phpcs.xml.dist --ignore=./Migrations/* ./src

FILE: src/[redacted]
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Undefined property:
   |       | PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode::$name in
   |       | /[redacted]/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php
   |       | on line 167
----------------------------------------------------------------------

Time: 4.72 secs; Memory: 6MB
```

This problem is caused solely by using array shapes (e.g. `@return array{bool, bool}`).

**Comment by ADmad** [comment]
:disappointed:
